eurodatacube/eodash

app/src/components/Map.vue

to fix zoom to a single regional poi mid sea

update zooming to single regional indicator poi

---

app/src/components/IndicatorMap.vue
app/src/components/Map.vue

use layers icon from material design

---

app/package-lock.json
app/package.json
app/vue.config.js

splits vendor chunk into separate chunks one per package to utilize browser parallel requests on it
adds a default image minification step (more compression could be done converting the png to jpeg etc)

Webpack tweaks

---

app/package-lock.json
app/package.json

point vue-papa-parse to local fork, audit

---

app/package-lock.json
app/package.json
app/src/components/IndicatorMap.vue

also update of package-lock by npm install is done

subaoi and aoi on indicator map colored based on time, clip works

---

app/src/components/IndicatorMap.vue
app/src/mixins/close.js
app/src/store/modules/indicators.js

added a getter to return indicator data masked to contain only rows where "Indicator Data" is not empty string
to deal with https://github.com/eurodatacube/eodash/issues/277

filter used values in indicator data

---

app/src/components/IndicatorData.vue

Only show percentage if no division by 0

---

app/src/components/IndicatorMap.vue

to take care of https://github.com/eurodatacube/eodash/issues/337

switching indicator now checks if to disable compare

---

app/src/components/IndicatorMap.vue
app/src/config/trilateral.js

This is just the beginning to tackle #325 and up for review if feasible like this. Still needs to fix the date on the left side to the same as the right side.

[WIP] Different map sources

---

app/src/config/trilateral.js

fixes legend url for rhone delta in trilateral
ad: https://github.com/eurodatacube/eodash/issues/367#issuecomment-658561994

change legend url

---

app/src/components/LineChart.vue

to take care of https://github.com/eurodatacube/eodash/issues/358
It was just missing check on nested properties, that we already have for bar charts

add watch for nested props to initiate chart reload for line chart

---

app/src/components/IndicatorMap.vue

to take care of https://github.com/eurodatacube/eodash/issues/313

fix indicator map initial fitToBounds being overridden by vue-leaflet

---

app/src/config/trilateral.js

new CO2 data

---

app/public/index.html
app/src/App.vue
app/src/components/DataPanel.vue
app/src/main.js
app/src/views/EmbedIframe.vue

@Schpidi i commented out the actual "embed chart" button for now to be sure, so we could merge this to production and test the iframes. If everything is well, I will re-add the button and we're good to go. Is that allright?

Iframe embed

---

app/src/config/esa.js
app/src/utils.js

adding and subtracting 45 minutes to fix naming issues
to take care of https://github.com/eurodatacube/eodash/issues/441

adding special date formatting function for s2

---

app/src/App.vue
app/src/views/Privacy.vue
app/src/views/Terms.vue

set app to fill height, add scroll containers for terms and privacy

---

app/src/views/Dashboard.vue

Responsive fixes

---

app/package-lock.json
app/package.json
app/src/config/esa.js

- cleanup of dependency, we dont really need, as we can request WKT in query from geodb directly
- npm audit fix

Remove wkx dep

---

app/src/components/NewsCarousel.vue

Carousel aspect ration

---

app/src/components/IndicatorMap.vue
app/src/scss/global.scss

fixes unreadable time selection and leaflet controls

Fix darkmode

---

app/src/App.vue
app/src/main.js

hotfix for safari 13 (and lower) compatibility

Watchmedia hotfix

---

app/src/components/IndicatorMap.vue

set legend width relative to viewport

---

app/src/views/Dashboard.vue

small fix to prevent console errors

fix attrs and on properties referencing

---

app/src/views/Dashboard.vue

fix dark mode button positioning

---

app/src/appConfig.js
app/src/components/NewsCarousel.vue

Adds the option to add an iframe to the carousel.

[WIP] Carousel iframe

---

app/src/scss/global.scss

add background to input

---

app/public/index.html
app/src/App.vue
app/src/components/GlobalFooter.vue
app/src/main.js
app/src/scss/global.scss
app/src/views/Dashboard.vue
app/src/views/EmbedIframe.vue
app/src/views/PageNotFound.vue
app/src/views/Privacy.vue
app/src/views/Terms.vue

This PR attempts to generally fix dark mode issues, by setting the background globally automatically instead of hardcoding white/dark background. It also adds footer to privacy, terms and 404 pages.
Also, iFrames in dark mode should look better now!

Fix iframe dark mode

---

app/src/components/IndicatorMap.vue
app/src/config/esa.js
app/src/store/modules/features.js

- fixes #728 
- drawnArea change is synced between all instances of indicatorMap (tabs)

Fix tabbed custom

---

app/src/components/FeatureTable.vue
app/src/components/IndicatorFilters.vue
app/src/components/IndicatorMap.vue
app/src/components/Map.vue
app/src/components/MapChart.vue
app/src/components/SelectionPanel.vue
app/src/main.js
app/src/plugins/charts.js
app/src/store/modules/features.js

Allows to filter out archived features

---

app/src/components/IndicatorMap.vue
app/src/config/esa.js
app/src/config/trilateral.js

- update CAMS start date to rolling 364 days ago
- move attribution text expanded and layersControl above time selection in indicator map (is now over instead of under)

Minor updates

---

app/src/components/IndicatorData.vue

made some lines thinner for e10a6 and n1 indicators

removed yellow from palette because of contrast issues

---

app/src/components/CenterPanel.vue

Make global indicators button a panel that is open by default

---

app/public/generate_files.py
app/src/components/IndicatorMap.vue
app/src/config/esa.js
app/src/config/trilateral.js

Solves #756 
Solves #835
Solves #806

Grouped displays

---

app/src/components/IndicatorData.vue

created individual datasets for N3 levels 

---

app/src/components/FullScreenButton.vue
app/src/components/IndicatorMap.vue

move fullscreen button lower

---

app/src/components/FeatureTable.vue

Table country restyle

---

app/src/components/DataPanel.vue
app/src/components/ExpandableContent.vue
app/src/scss/global.scss
app/src/views/Privacy.vue
app/src/views/Terms.vue

- Fix issue #828 
- Fix issue #888 
- automatically expand content when right panel is maximized
- fix mobile overlay and proportions

Fix issue #828

---

app/src/components/DataPanel.vue

Fix graph overlap with story text

---

app/src/components/DataPanel.vue
app/src/components/ExpandableContent.vue
app/src/scss/global.scss
app/src/views/Dashboard.vue
app/src/views/Privacy.vue
app/src/views/Terms.vue

2021 04 UI updates

---

app/public/data/trilateral/privacy.md

Fixed some typos and the table.

Fix and harmonize privacy.md files

---

app/src/components/CustomDashboardGrid.vue
app/src/components/DataPanel.vue
app/src/components/IndicatorData.vue
app/src/components/IndicatorMap.vue

Custom dashboard

---

app/src/components/CustomDashboardGrid.vue
app/src/store/modules/dashboard.js
app/src/views/DashboardCustom.vue

This PR closes #1018 and #1019.
Additionally, it includes a fix for long Markdown fields (auto overflow), and it always displays id and editKey in the url, if they are available.

Custom dashboard improvements

---

app/src/appConfig.js
app/src/components/NewsCarousel.vue
app/src/utils.js
app/src/views/Challenges.vue

- relative ones opened in the same tab
- external ones opened in a new tab
fixes #1034

newsCarousel now accepts any url link under new 'href' parameter

---

app/public/eodash-data/stories/E200.md

added the new story for E200 starting from E1.md story.

Created E200 Story

---

app/src/appConfig.js

fix for e13c on trilateral

---

app/src/components/IndicatorMap.vue

fix: disable map scroll when v-select is focused

---

app/src/components/IndicatorData.vue
app/src/views/Dashboard.vue

- Removes unnecessary z-index causing nav drawer to hide behind central map
- Removes a console log

2022 03 10 fixes

---

app/src/components/GlobalHeader.vue

fix: fix missing indicator and country filters on mobile

---

app/src/main.js
app/src/views/DashboardCustom.vue

feat: always allow story mode by entering it via URL

---

app/src/components/CustomDashboardGrid.vue
app/src/components/IndicatorData.vue
app/src/components/IndicatorMap.vue
app/src/components/IndicatorTimeSelection.vue

This PR is the second attempt to modularize time selection

1317 modularize time selection

---

app/public/data/trilateral/about.md
app/src/components/ThemesLandingPage/Hero.vue
app/src/config/themes.json
app/src/views/ThemeSinglePage.vue
app/src/views/ThemesLandingPage.vue

This PR adds initial adjustments regarding trilateral stories appearance:
- update of trilateral welcome text
- update of landing page hero text and datasets section text
- update of theme page hero text and datasets section text
- update of theme catch phrases, descriptions and colors (not complete yet)
- small update of the header size on mobile to fit longer theme catch phrases

Text updates and header height adjustments

---

app/src/components/CustomDashboardGrid.vue
app/src/config/stories.json
app/src/views/DashboardCustom.vue

This PR adds the "image block" feature, and an ability to add image captions to images.
Also, the titles of elements are now hidden in story mode.

Improve image elements 2

---

app/src/components/CustomDashboardGrid.vue

This change includes an uncommitted change from last time... sorry

fix: icons for collapse/expand

---

app/public/eodash-data/stories/N1.md

fix: use https link to prevent mixed content warning

---

app/src/components/GlobalHeader.vue
app/src/components/ThemesLandingPage/Hero.vue
app/src/components/ThemesLandingPage/StoriesGrid.vue
app/src/config/themes.json
app/src/views/DashboardCustom.vue

This PR contains a few smaller fixes to the stories UI

Story layout improvements

---

app/src/components/GlobalHeader.vue

fix: make sure to always show hamburger menu on mobile

---

app/src/views/Welcome.vue

Updated headline on old interface

Updated headline on old interface

---

app/src/components/GlobalHeader.vue
app/src/components/Modal.vue
app/src/components/Modal/SaveDashboardForm.vue
app/src/components/ThemesLandingPage/NewsletterBanner.vue
app/src/scss/global.scss
app/src/views/DashboardCustom.vue
app/src/views/Feedback.vue

Various modal fixes: show in story mode, correct loading with id, css adjustments and more...

fix: various modal fixes

---

app/src/components/CustomDashboardGrid.vue
app/src/views/DashboardCustom.vue

This PR better separates custom dashboard config from story config, enabling having both in parallel without interference

Fix custom dashboard bleed into stories

---

app/src/components/CustomDashboardGrid.vue

This PR adds page information to the query when navigating through story pages (and sets the page if the url contains a query param on load)

Add page information to query

---

app/package-lock.json
app/src/views/Dashboard.vue

@silvester-pari 
@spectrachrome

Resizable side content

---

app/src/components/IndicatorTimeSelection.vue

fix: initial comparetime set when compareDisplay configured

---

app/src/App.vue

This PR adds a fix for the route watcher, which caused some issues with zooming to predefined AOIs.
An informal comment has been added for future debugging.

fix: setTImeout to fix zooming to AOI

---

app/src/appConfig.js
app/src/components/IndicatorFilters.vue
app/src/components/map/CustomAreaButtons.vue
app/src/config/esa.js
app/src/views/Dashboard.vue

see https://github.com/eurodatacube/eodash/issues/1617

20221010 UI fixes

---

app/src/components/GTIF/GTIFIndicatorFilters.vue

This PR improves the GTIF sidebar functionality:
- close POI sidebar on POI selection
- keep domain selected on POI selection
- auto-select correct domain on page reload (if POI in url query)

Improve sidebar

---

app/src/components/map/LayerSwipe.vue
app/src/helpers/mapConfig.js
app/src/views/EmbedIframe.vue

This PR fixes the iframed map display

Fix iframed map

---

app/src/components/GTIF/AdminBordersLayers.vue
app/src/components/map/LayerControl.vue
app/src/components/map/Map.vue
app/src/components/map/SpecialLayer.vue
app/src/components/map/layers.js

- hide/show admin layers in layercontrol (1 group)

Admin borders layercontrol

---

app/src/components/CustomDashboardGrid.vue

fix: z-index of mobile story navigation

---

app/src/components/map/Map.vue
app/src/components/map/layers.js
app/src/components/map/timeLayerUtils.js
app/src/helpers/mapConfig.js

- fixes FNF indicator and those where alos and sentinel-1 inputData are both used
- fixes #1727

consider inputData as an array for modifying visualization request parameters

---

app/src/components/DataPanel.vue
app/src/components/GlobalHeader.vue
app/src/store/index.js
app/src/views/Dashboard.vue
app/src/views/ThemesLandingPage.vue

Global about button

---

app/src/components/IndicatorFilters.vue

fix: reset filters on mounted

---

app/src/components/GTIF/GTIFBreadcrumbs.vue
app/src/components/GTIF/GTIFIndicatorFilters.vue
app/src/views/Dashboard.vue

Visual improvements for GTIF (November 14, 2022)

---

app/src/components/map/FilterControls.vue

Implement linear NESW slider for Energy Transition `aspect` filter value

---

app/src/components/map/FilterControls.vue

feat: export current map view as png

---

app/src/components/map/FilterControls.vue

https://user-images.githubusercontent.com/94269527/222695210-e459d88f-8351-44a4-8f94-59b7aa430c86.mov

Shrink vertical size of NESW control by a lot

---

app/src/components/DataPanel.vue
app/src/config/esa.js
app/src/config/trilateral.js
app/src/helpers/customAreaObjects.js

close https://github.com/eurodatacube/eodash/issues/2162

Add Draw custom area for chla/tsmnn data 

---

app/src/config/gtif.js

* Use human-friendly names for solar and green roof layers
Fixes #2128

Various small fixes in GTIF rooftops

---

app/src/components/map/LayerSwipe.vue

close https://github.com/eurodatacube/eodash/issues/2067
ref https://github.com/eurodatacube/eodash/issues/2049

Compare slider fixed for retina displays

---

app/src/components/CustomDashboardGrid.vue
app/src/components/map/Map.vue
app/src/store/modules/dashboard.js

Closes #2149
TODO: Insert clone at the position after the current element (currently is inserted at the very end)

Add element cloning functionality

---

app/public/data/gtif/markdown/SOL1_TEP_LP.md
app/public/data/gtif/markdown/SOL1_TEP_RP.md

Use consistent nomenclature for low, regular and high performance and efficiency photovoltaics

---

app/src/components/ThemesLandingPage/StoriesNews.vue

Space for Climate Protection award

Update news 

---

app/src/components/IndicatorData.vue
app/src/components/map/layers.js
app/src/config/gtif.js

Minor adaptations of SOL1 display

Gtif staging

---

app/public/data/gtif/markdown/AQ.md
app/public/data/gtif/markdown/AQ1.md
app/src/components/IndicatorFiltersSidebar.vue
app/src/config/gtif.js

fixes #2277 
fixes issue with bottom padding of navigation panel

Gtif fixes jul18

---

app/src/helpers/customAreaObjects.js

no longer returns array but object, need to get data from first key, i.e. usually band 1 (b1)

fix: updated acces to return data from nasa api

---

app/src/components/DataMockupView.vue
app/src/components/IndicatorData.vue
app/src/components/LineChart.vue
app/src/config/gtif.js

Integrates the Wind Variability (monthly average wind speed) aggregated on a ZSP level to Solar Energy tool
close #2235
Can be seen on https://gtif-testing.eox.at/gtif-wind-variability/

chore: integrate wind variability chart for REP1

---

app/src/config/gtif.js
app/src/config/layers.js

closes https://github.com/eurodatacube/eodash/issues/2143

chore: add s1 eodc layers as base

---

app/src/components/DataMockupView.vue

closes https://github.com/eurodatacube/eodash/issues/2097
can be seen on https://gtif-testing.eox.at/gtif-co2red-sol1/

chore: add co2 reduction for SOL1 table

---

app/src/config/layers.js
app/src/config/trilateral.js

closes https://github.com/eurodatacube/eodash/issues/2373
can be seen on https://eodash-trilateral-testing.eox.at/stereographic-polar-basemaps/

chore: add stereographic terrain light baselayers

---

app/.eslintrc.js
app/src/components/DataPanel.vue
app/src/components/IndicatorData.vue
app/src/components/IndicatorFiltersDemo.vue
app/src/components/SelectionInfoBar.vue
app/src/components/map/CustomAreaButtons.vue
app/src/config/esa.js
app/src/config/gtif.js
app/src/config/trilateral.js
app/src/shTimeFunction.js
app/src/store/modules/indicators.js
app/src/utils.js

From [#2388](https://github.com/eurodatacube/eodash/issues/2388#issuecomment-1838774392)

Minor Datapanel UI updates

---

.github/workflows/feature-branch_deploy.yml
.github/workflows/gtif-demo_deploy.yml
.github/workflows/gtif-staging_deploy.yml
.github/workflows/production_deploy.yml
.github/workflows/staging_deploy.yml
app/public/shConfig.js
app/src/config/ideas.js

cc @UndeadFairy 
ref: https://github.com/eurodatacube/eodash/issues/2434

chore: create configs for auxiliary data for ideas_i4

---

app/src/components/DataMockupView.vue
app/src/components/IndicatorData.vue
app/src/config/gtif.js

- also fix statistics and chart for SOL1
close https://github.com/eurodatacube/eodash/issues/2008

feat: implement statistics and chart for SOL2

---

app/src/components/IndicatorFiltersPanel.vue
app/src/store/modules/indicators.js

- speeds up subcollection loading by parallelization
- fixes GeoDB sourced datasets fetching
- adds reset map extent on explore button for GTIF

production deployment GTIF 26.3.2024

---

app/package-lock.json
app/package.json
app/public/data/storytelling-md/Earth Observing Dashboard-3.md
app/public/data/storytelling-md/new-storytelling-demo.md
app/src/components/ThemesLandingPage/Hero.vue
app/src/components/ThemesLandingPage/StoriesNews.vue
app/src/config/stories.json
app/src/main.js
app/src/views/DashboardCustom.vue
app/src/views/StoryEditor.vue
app/vue.config.js

Updating story and adding info to news section

Merging of new stories branch

---

app/.gitignore
app/src/components/IndicatorData.vue
app/src/components/SelectionInfoBar.vue
app/src/components/map/Map.vue
app/src/components/map/MapOverlay.vue
app/src/components/map/SpecialLayer.vue
app/src/config/esa.js
app/src/config/layers.js
app/src/helpers/customAreaObjects.js
app/src/utils.js

- adds tooltip aggregation and handling for multiple selectable/tooltipped layers - could be useful for GTIF AT Demonstrator
- integrates CROPOM subcounty and microregion as individual collections
close https://github.com/eurodatacube/eodash/issues/2565
close https://github.com/eurodatacube/eodash/issues/2342

Cropom multilayer integration

---

app/src/components/DataPanel.vue
app/src/components/Modal/MinesweeperDialog.vue
app/src/components/SpeciesList.vue
app/src/components/map/Map.vue
app/src/config/ideas.js
app/src/config/layers.js
app/src/plugins/minesweeper/board.js
app/src/plugins/minesweeper/index.js

Minesweeper Fixes 06-2024

---

app/src/components/GlobalHeader.vue
app/src/config/stories.json
app/src/config/themes.json
app/src/config/trilateral.js
app/src/main.js

- icon: `mdi-lightning-bolt` 
- description on story page: `Tracking the Effects of Extreme Events`
- title: `Extreme Events`
- story page has no special "image" yet
- color: #a1280a
https://eodash-trilateral-testing.eox.at/extreme-events-theme/
closes https://github.com/eurodatacube/eodash/issues/2603

chore: add extreme events theme

---

app/package-lock.json
app/package.json
app/public/data/storytelling-md/Earth Observing Dashboard-3.md
app/src/App.vue
app/src/components/OLExportButton.vue

Depends on a release of new eoxmap version including https://github.com/EOX-A/EOxElements/pull/1046
and bump of a version here

Story editor updates

---

app/src/components/StacInfo.vue
app/src/components/map/Map.vue

- bugfix release
- adding map scaleline

Production deploy RACE + trilateral 24.7.2024

---

app/src/App.vue

removing transparent for background

fix: dark mode and loading indicator

---

app/src/App.vue
app/src/components/IndicatorData.vue
app/src/config/trilateral.js
app/src/utils.js

- Fix E13b chart regression.
- Removing date overrides in trilateral, as we will now be generating all items correctly in the catalog builder.
- fix Transparency issue of the main app regression
Depends on https://github.com/eurodatacube/eodash-catalog/pull/180 being merged and built.

WIP Production deploy 4.8.2024

---

.github/workflows/feature-branch_deploy.yml
app/src/components/GlobalHeader.vue
app/src/components/ThemesLandingPage/StoriesGrid.vue
app/src/views/ThemeSinglePage.vue

* Updated deprecated artifacts version

feat: removing story header; resetting theme when exploring data

---

app/src/components/map/timeLayerUtils.js
app/src/config/trilateral.js

fixed incorrect link to vector source for geoglam

fix: issue updating layer time correctly for array times; 

---

app/public/data/storytelling-md/eoadashMarkdown_ANTARCTIC_LOWS.md

Final updates of antarctic story

---

app/public/data/storytelling-md/el_nino_part_4.md

Updated with actual legends of GEOGLAM, referring also time period
