- app/src/components/IndicatorMap.vue
- app/src/config/esa.js
- app/src/config/trilateral.js
new config in indicator definition: `largeTimeDuration:true` enables that compare image time selection is preset at closest time one year earlier
otherwise use first time entry as before
> default comparsion time is one year behind for air quality data

- app/src/components/IndicatorMap.vue
this allows to set for example maxMapZoom, minMapZoom or bounds per 
layer
> add layermapping as another source of map defaults for indicator map

- app/src/components/IndicatorData.vue
- app/src/config/esa.js
- will make it configurable so that by default, it rounds to 2 decimals for tooltips, but we will be able to set per-indicator-type number of decimals to any number or set it to -1 to disable this behavior completely. Config allowing this is in `indicatorsDefinition.<indicator>.maxDecimals`.
- individual tooltip definitions used in indicatorData (like for E10a8) will still overwrite this behavior completely
- data downloadable would download the full values
> rounding decimals

- app/src/views/Dashboard.vue
proposition to move the dark mode toggle to the left part of the footer on desktop, and into the drawer menu header on mobile
> Move darkmode toggle

- app/src/scss/global.scss
> Prevent menu from displaying over fullscreen dialog

- app/src/components/DataPanel.vue
- app/src/components/FullScreenButton.vue
- app/src/store/index.js
- app/src/views/Dashboard.vue
Fixes #689.
The following changes were made:
1) The code that hides the fullscreen button on Safari and iOS was removed.
2) A new property, `isFullScreen` was added on the root Vuex store.
3) Added code logic that hides the header, the left sidebar, the footer as well as some other mobile elements when `isFullScreen` is toggled on.
4) iPhone does not support fullscreen(more on that [here](https://stackoverflow.com/a/46544156/8157383)). I manually trigger fullscreen on such devices without using `vue-fullscreen`
> Fix fullscreen mode on Safari and iOS

- app/src/components/DataPanel.vue
The [clearSelection()](https://github.com/eurodatacube/eodash/blob/fix-custom-area-close/app/src/components/DataPanel.vue#L588) function references `this.$refs.indicatorMap` which is not rendered in the case of `customAreaIndicator && !expanded` in the [original code](https://github.com/eurodatacube/eodash/blob/staging/app/src/components/DataPanel.vue#L123). 
Therefore I added an [invisible indicatorMap](https://github.com/eurodatacube/eodash/blob/fix-custom-area-close/app/src/components/DataPanel.vue#L155), and an [additional check](https://github.com/eurodatacube/eodash/blob/fix-custom-area-close/app/src/components/DataPanel.vue#L589) if there are multiple indicatorMaps or just this single one.
> fix: keep indicator map (but hide it) to fix #828

- app/src/App.vue
added check to look for archived indicators if provided indicator in url is not found in non archived indicators.
Fixes #945
> Bug fix for archived indicator filter in url not working

- app/src/components/IndicatorData.vue
- only loops through `indicatorObject.times` in custom AOIs to prevent infinite loops on other indicators
> Fix infinite loop

- app/src/views/DashboardCustom.vue
This PR adds some information during editing and viewing mode of custom dashboards.  
Editing mode:
Viewing mode:
Closes #1038
See https://github.com/eurodatacube/eodash/issues/1040#issuecomment-929128346
> Add disclaimer and reference to tos for unofficial custom dashboards

- app/src/components/DataPanel.vue
- app/src/components/IndicatorMap.vue
- fixes WMS layers case when different time entries had different parameters configured because of inputData (baseurl, layers/styles etc. was not passed)
- refactors mergedConfigs method to become a computedProp to avoid triggering it hundreds of times unnecessarily
- note that switching between WMS/WMTS/XYZ protocol for different time entries is not possible and would need some more implementation
> Fix case when input data changes for different time entries

- app/src/views/DashboardCustom.vue
This tiny pull request fixes a typo that would break the form's loading indicator and wraps the `addToMailingList` call in a try/catch block, so it still navigates to the links modal even if the mailing list call fails.
Closes #1257
> Fix loading indicator and catch errors when saving new custom dashboard

- app/src/components/CustomDashboardGrid.vue
- app/src/components/IndicatorData.vue
- app/src/components/IndicatorMap.vue
- app/src/components/IndicatorTimeSelection.vue
This PR aims to extract the time selection feature into its own component, while at the same tame reducing a bit the size of `IndicatorMap.vue`.
Todo:
Closes #1317
> feat: modularize time selection component

- app/package-lock.json
- app/package.json
- app/src/components/CustomDashboardGrid.vue
This PR adds the medium-zoom pacakge to enable automatic zoom highlighting of images in a custom dashboard text element.
It also uses the nice `:only-child` pseudoselector to check if there is only one image/video/iframe in the text block and apply 100% max-height to it.
Closes #1325
> Improve image display

- app/src/components/map/CenterMap.vue
- app/src/components/map/Cluster.js
- app/src/components/map/formatters.js
- app/src/components/map/map.js
- app/src/store/modules/features.js
This PR brings the two missing features "sub-AOI" and "hover overlay" to the center map.
The tooltip overlay behaves slightly different to the current application. In the current application, the tooltip will display the words "Reference Area" when hovering over a sub-AOI. Now it will display the actual information, and placing the tooltip at the position of the indicator poi belonging to the reference area. Please let me know if this change is in your interest.
The subaoi-Geometries are the normal subaois from indicator as seen on the center map of the current applications. Inverse Polygons (as seen on indicator maps) are not yet implemented.
This PR changes the WKT-parsing to ol geometries. This will temporarily break some indicator maps.
Features from …
> Subaoi overlay

- app/src/components/IndicatorMap.vue
- app/src/components/IndicatorTimeSelection.vue
- app/src/helpers/customAreaIndicator.js
- app/src/helpers/customAreaObjects.js
- app/src/helpers/mapConfig.js
- app/src/utils.js
> Refactor IndicatorMap.vue

- app/src/App.vue
- app/src/components/CustomDashboardGrid.vue
- app/src/components/GlobalFooter.vue
- app/src/views/DashboardCustom.vue
This PR introduces a more versatile story layout for mobile screens:
- horizontal story layouts (columns) from desktop are translated into vertical ones on mobile
- all text fields can be expanded by swiping
- number of pages on mobile is equal to page number on desktop
Some images:
> Stories mobile layout

- app/src/components/CustomDashboardGrid.vue
This PR fixes
- an issue where between `xs` and `md` breakpoints neither mobile nor desktop mode was enabled
- page number consistency/refresh by calculating the number of rows only once at startup
> Stories mobile layout fixes

- app/src/components/CustomDashboardGrid.vue
This PR fixes an issue where in some occasions the `#headerRow` would load only after the `navigationButtonVisible` computed property tried accessing it, resulting in a broken navigation button with missing current/total page display.
> fix: wait for component mount before retrieving headerRow height

- app/src/components/CustomDashboardGrid.vue
This PR dynamically creates image titles based on the entered description
> fix: use image description as img title

- app/src/components/CustomDashboardGrid.vue
This PR sanitizes line breaks so they can be used in image descriptions
> fix: sanitize linebreaks in image description

- app/src/components/CustomDashboardGrid.vue
This PR fixes an issue where on Chrome browsers, when zoomed in, the offsetTop would be calculated in a slightly different manner, resulting the navigation arrows not showing in the story mode. This is more of a workaround than a fix, but didn't find any cleaner solution after some research...
Also see this [comment referencing offset in browsers](https://api.jquery.com/offset/):
> Also, dimensions may be incorrect when the page is zoomed by the user; browsers do not expose an API to detect this condition.
> fix: add offset calculation buffer

- app/src/components/CustomDashboardGrid.vue
- app/src/components/GlobalFooter.vue
This PR tries to fix the window resizing bug in stories by introducing a waiting period to a)recalculate vh and b) reset the position. When going from mobile to desktop now it seems to always reset to the first page, but that's not a big issue, th important thing is it is not broken anymore.
> Fix height calculation and navigation reset after window resize

- app/src/components/GlobalHeader.vue
- app/src/views/Dashboard.vue
This PR fixes the issue of the broken "explore" navigation button in the header caused by a `selectedIndicator` stored in the store. Also now, each time the user navigates away from the explore page, the selected indicator is reset. This causes just a slight inconvenience when navigating back from a custom dashboard (takes a bit longer to load), but brings the benefit of the `selectedIndicator` not bleeding into the rest of the application and causing trouble.
> Fix selected indicator bleeding

- app/src/components/IndicatorData.vue
- app/src/components/IndicatorMap.vue
- app/src/config/trilateral.js
- app/src/helpers/customAreaObjects.js
- generalized call to the `/timelapse` endpoint and extended configs so that customAreaIndicator is used also for CO2 + CO2 diff + NO2 OMI diff
- updated rescale range for OMI NO2 yearly to match the NO2 monthly OMI + added reference to the same legend
> Timelapse endpoint extend

- app/src/components/FeedbackButton.vue
- app/src/components/GTIF/GTIFBreadcrumbs.vue
- app/src/components/GTIF/GTIFHeader.vue
- app/src/components/GTIF/GTIFHeaderNavItem.vue
- app/src/views/ScrollyFrame.vue
This pull request contains changes to the GTIF brand as requested in Mariangela's document from October 5, 2022. The following changes were made:
* Add support for indentation of navigation items in the sidebar
* Add new sub-header component containing the breadcrumbs.
* Update styles for the normal and hovered states of the navigation items
* Update color of the feedback button
> Customize GTIF navigation menu and add breadcrumbs

- app/src/components/map/Map.vue
This PR improves the stability of zooming to the extent of a POI after selection.
Centering to an inverse subAOI might still be a little off, this issue will be fixed in a another PR.
> fix: quick fix to improve zoom to extent

- app/src/components/map/Map.vue
- app/src/components/map/SubaoiLayer.vue
This PR adds the following:
- prioritize preset view (if defined) over subAOI when selecting an indicator
- only drag user back to inverse subAOI if map was moved via real user pan interaction
- fix a vue-key used for destroying map components
Note: this PR cherry-picked a commit from #1653, which should be treated first.
> Fix: preset view & pan restrictions

- app/src/components/map/Map.vue
- app/src/components/map/SubaoiLayer.vue
This PR fixes wrong dragbacks after userinteractions on some global indicators by disabling this functionality entirely for such indicators.
> prevent dragback on global indicators

- app/src/components/map/layers.js
This PR makes errors when fetching GeoJSON features fail silently. This could happen when a faulty JSON-file is fetched, or the file is not available (e.g. invalid bounding box)
> fix: make geojson fetch errors fail silently

- app/src/components/IndicatorFilters.vue
- app/src/components/map/Map.vue
This PR adds a check if the current indicator is actually a global indicator, and displays the iframe and add-to-dashboard-buttons only on the map if true.
By mistake added a commit of the other branch too, sorry
> Global indicator buttons

- app/src/components/map/Map.vue
- app/src/utils.js
This PR introduces one possible solution to reported infinite update loops via a registry object.
The problem seemed to be the manipulation of the arrays as a "cleaning" routine. This caused the `watchers` to fire, again manipulating the arrays.
Since this cleaning of invalid data entries should be necessary only once per indicator, later retrievals now always access the already clean indicator object.
Closes #1755
> feat: create indicator registry

- app/src/components/DataPanel.vue
Before when expanding a POI that was text-only in the Datapanel the layout was inconsistent with our other POIs
vs
With this PR the text should always stay on the right side when expanded
> fix: consistent layout when expanding datapanel with text only

- app/src/components/AdminLayersInfoBar.vue
- app/src/components/DataPanel.vue
- app/src/components/map/DarkOverlayLayer.vue
- app/src/components/map/Map.vue
- app/src/components/map/SpecialLayer.vue
- app/src/config/gtif.js
- app/src/store/modules/features.js
Minor refactor - moving austria overlay from admin layers to a separate component
Also fixes regression of admin layers not showing correctly in list after it has been made configurable which indicator has which admin borders
> move dark overlay to a separate component

- app/src/appConfig.js
It is only possible to test the GTIF brand on another device as long as there is a dedicated DNS server in the network and as long as `appConfig.js` contains the appropriate domain names. 
This pull request adds three new domain names, each one ending with a `.home` TLD that is commonly agreed to be safe for home network usage: 
* [`race.eox.home`](http://race.eox.home:8812)
* [`trilateral.eox.home`](http://trilateral.eox.home:8812)
* [`gtif.eox.home`](http://gtif.eox.home:8812)
TODO: Into which branch should we merge this so it works for both `staging` and `gtif_staging`? Maybe just `gtif_staging` for now since the other two brands can be distinguished via IP/name?
> chore: add entries for .home domains for use with home dns

- app/src/components/map/SpecialLayer.vue
- app/src/config/gtif.js
`config.tooltip = true` - enables tooltip from all properties of feature object
`config.allowedParameters` - if config.tooltip is true-ish, this limits the keys that are printed in the tooltip
`config.tooltip.tooltipFormatFunction` - if configured, will be used with the clicked feature as first argument and should return list of strings
if `config.tooltip.trigger === 'singleclick'` the tooltip will be displayed on click, otherwise as default it will be on hover
> feat: separate tooltip and selection behavior

- app/src/components/CustomDashboardGrid.vue
This pull requests provides a simple change which fixes the freezing in custom dashboards on Firefox, something which is especially noticeable when opening the dialog for the second time since it causes the entire page to freeze.
Read more [in this GitHub issue thread of the `vuetify` project](https://github.com/vuetifyjs/vuetify/issues/8459).
> fix: prevent recursive focusin handler calls by setting `retain-focus`  to false in dialog

- app/src/components/CustomDashboardGrid.vue
- app/src/components/IndicatorData.vue
- app/src/components/map/Map.vue
- app/src/components/map/SpecialLayer.vue
- app/src/config/trilateral.js
- app/src/utils.js
PR Adds two way interaction on time axis between main map and a chart (both custom area chart and the standard data chart)
Clicking on a dataset point on chart sets the map time closest to selected time. Same happens if shift or ctrl is hold for compare time selection (if compare is enabled). There is currently no counterpart of this functionality for ctrl/shift on mobile.
Similarly currently selected time/compare time is shown on a chart as a vertical annotation line.
Test deployments:
- https://eodash-testing.eox.at/map-chart-time-interaction/
- https://eodash-trilateral-testing.eox.at/map-chart-time-interaction/
- https://gtif-testing.eox.at/map-chart-time-interaction/
> Map chart time interaction

- app/src/components/map/SliderTicks.vue
Updates the slider ticks to derive the positions of year marks from the tick array reactively so that all marks are accurately placed. This negates the drift or just outright wrong placement of the year marks.
https://github.com/eurodatacube/eodash/assets/94269527/6c9922d2-7cea-49ab-942a-8ebbca4f5ea3
> Fix inaccurate year marks in `SliderTicks` component

- .github/workflows/feature-branch_deploy.yml
- .github/workflows/gtif-demo_deploy.yml
- .github/workflows/gtif-staging_deploy.yml
- .github/workflows/production_deploy.yml
- .github/workflows/staging_deploy.yml
- app/package-lock.json
- app/package.json
- app/public/shConfig.js
- app/src/appConfig.js
- app/src/components/map/Map.vue
- app/src/config/esa.js
- app/src/config/trilateral.js
- app/src/main.js
- app/vue.config.js
Agreed with Anca and Patrick in weekly/bi-weekly
Also incorporates some data updates
> Bringing geosearch component to production

- app/src/config/gtif.js
- app/src/config/layers.js
close https://github.com/eurodatacube/eodash/issues/2465
Needed to move the protected areas to analysis layers otherwise tooltip can not be configured now, I hope that is fine
https://gtif-testing.eox.at/protected-areas-tooltips/?indicator=REP1_1
> feat: integrate tooltip of protection zones

- app/src/components/OLExportButton.vue
- app/src/components/map/layers.js
* fix: adding ids to layers to make sure reordering in layercontrol works
* chore: linting
* fix: wrong layer order exported for analysis layers
* feat: implementation of custom area features in map export, fixed max-height of content
> fix: reordering logic and map export state for custom area data (#2656)

- app/src/components/OLExportButton.vue
* made sure only create map export string if dialog is open, should help with performance
* made sure style is exported correctly
> fix: multiple fixes related to map export function
